### PR TITLE
Exercises, part 1

### PR DESCRIPTION
**Pull request by grunweg**
To be continued

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Is 1(e) intended to define `𝔽ₙ` and convert it into `ZMod n`? Otherwise I'm not sure what you mean by parsing individual digits.
This is possible using `Mathlib.Util.Superscript`, but that is outside the scope of the covered material...

**Comment by grunweg** [comment]
> Is 1(e) intended to define `𝔽ₙ` and convert it into `ZMod n`? Otherwise I'm not sure what you mean by parsing individual digits. This is possible using `Mathlib.Util.Superscript`, but that is outside the scope of the covered material...

It is supposed to turn `𝔽₂₃` into `ZMod 23` (though, perhaps I should make the notation \Z₂₃ instead): I was thinking of manually matching on the unicode digits and converting that into the right number by hand (basically re-inventing `Util.Superscript`). And the fact that `match` statements were not discussed yet is one of the reasons this has three stars: it does require extra knowledge.

**Comment by grunweg** [comment]
I should add: overall, these exercises are rather hard. I'm happy to dial them down/add some more doable ones.
(And this is perhaps just the first half of my ideas; I can add the remaining ones tomorrow.)

**Comment by fpvandoorn** [comment]
Thanks. I'll just merge as-is now, feel free to add more in the same file if you have more (and you can announce on Zulip if you think it's ready for people to try them).

**Comment by fpvandoorn** [comment]
I don't think hard exercises are bad, we can discuss them during the seminar if needed.

**Pull request merged**
